project_id = "iqrypgqdhpanqjqnxtap"

[functions.create-checkout-session]
verify_jwt = false

[functions.create-portal-session]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.create-editor]
verify_jwt = false